defaults:
 - _self_
 - data: abstracts
 - eval: eval
 - endtoend: baseline_outputs
#  - attribute_gen_method: "single_call"
#  - paper_loop: "multiple"
retry_type: "shuffle"
difficulty: "hard"
debug: False
wandb: False
endtoend: null
attribute_gen_method: null
paper_loop: null
timestamp: ???
mode: ???
results_path: ???
notes: null