defaults:
 - _self_
 - data: abstracts
 - eval: eval
 - endtoend: baseline_outputs
 - schematizer: null
 - populator: null
debug: False
wandb: False
endtoend: null
schematizer: null
populator: null
timestamp: ???
mode: ???
results_path: ???
notes: null