_id: "name-${.name}"
name: "hierarchical_outputs"
prompt_path: "data/prompt_ver3.json"
model_type: "gpt3.5"
max_length: 60
num_commonality: 1
attribute_gen_method: "single_call"
paper_loop: "multiple"
scheme_source: "abstract"
value_source: "abstract"