_id: "name-${.name}"
name: "ours_outputs"
prompt_path: "data/prompt_ver2.json"
model_type: "mixtral"
max_length: 100
num_commonality: 3
attribute_gen_method: "single_call"
paper_loop: "multiple"
scheme_source: "abstract"
value_source: "abstract"